config/routes.rb
Rails.application.routes.draw do
  resources :data
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'data#index'
end

app/models/account.rb
class Account < ApplicationRecord
   # belongs_to :account_classifications , foreign_key: "account"
  #  belongs_to :groupings, foreign_key: 
    has_many :data
end

app/models/account_classification.rb
class AccountClassification < ApplicationRecord
    #belongs_to :accounts
    #has_many :groupings
    #belongs_to :names_classes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
    has_attached_file :file_attch,  :url => "/files/:basename.:extension"
    do_not_validate_attachment_file_type :file_attch
    has_many :accounts
end

app/models/grouping.rb
class Grouping < ApplicationRecord
   # belongs_to :accounts , foreign_key: "account"
  #  belongs_to :account_classifications, foreign_key: "group_account"
end

app/models/names_class.rb
class NamesClass < ApplicationRecord
  #  has_many :account_classifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
require 'pry'
class DataController < ApplicationController
  before_action :set_datum, only: %i[ show edit update destroy ]

  # GET /data or /data.json
  def index
    @data = Datum.all
  end

  # GET /data/1 or /data/1.json
  def show
    id_file = @datum.id
    @getting_data = Records.new.get_data(id_file)
    @classes = NamesClass.all
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data or /data.json
  def create
    @datum = Datum.new(datum_params)
    id = @datum.id
    respond_to do |format|
      if @datum.save
        id = @datum.id
        @data = ParseData.new.get_inform(datum_params,id)
        format.html { redirect_to @datum, notice: "Данные успешно загружены" }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1 or /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: "Datum was successfully updated." }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1 or /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url, notice: "Datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def datum_params
      params.require(:datum).permit(:name,:file_attch)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_with(model: datum, local: true) do |form| %>
  <% if datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
        <% datum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
<% end %>

<%= simple_form_for @datum, url: data_path do |form| %>
  <%= form.input :file_attch, as: :file , label: 'File:'%>
  <br>
  <%= form.submit "Click Here" %>
<% end %>

app/views/data/edit.html.erb
<h1>Editing Datum</h1>

<%= render 'form', datum: @datum %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Файлы</h1>

<table>
  <thead>
    <tr>
      <th>Имя файла</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.file_attch_file_name %></td>
        <td><%= link_to 'Показать', datum %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить новый файл', new_datum_path %>

app/views/data/new.html.erb
<h1>Добавьте файл</h1>

<%= render 'form', datum: @datum %>
<br>
<%= link_to 'Назад', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Имя файла:</strong>
  <%= @datum.file_attch_file_name%>
</p>
<br>
<table border="1" width="70% "cellpadding="4" cellspacing="0">
  
  <tr>
    <th rowspan="2">Б/сч</th>
    <th colspan="2">ВХОДЯЩЕЕ САЛЬДО</th>
    <th colspan="2">ОБОРОТЫ</th>
    <th colspan="2">ИСХОДЯЩЕЕ САЛЬДО</th>
  </tr>

  <tr>
    <th>Актив</th>
    <th>Пассив</th>
    <th>Дебет</th>
    <th>Кредит</th>
    <th>Актив</th>
    <th>Пассив</th>
  </tr>

  <% @id_class = @getting_data[0]["id_class"] %>
  <tr>
    <th colspan="7" style="text-align:center">
      <p><%= @classes.where("id = ?",@id_class).first[:name]%></p>
    </th>
  </tr>
  <% @getting_data.each do |record| %>
    <% if record["id_class"]!= @id_class%>
      <% @id_class = record["id_class"]%>
      <tr>
      <th colspan="7" style="text-align:center"><p><%= @classes.where("id = ?",@id_class).first[:name] %></p></th>
      </tr>
    <%else%>
      <tr>
      <% if record["account"]/100==0 %>

        <td><b><%= record["account"] %></b></td>
        <td><b><%= record["in_assets"] %></b></td>
        <td><b><%= record["in_passive"] %></b></td>
        <td><b><%= record["credit"] %></b></td>
        <td><b><%= record["debit"] %></b></td>
        <td><b><%= record["out_assets"] %></b></td>
        <td><b><%= record["out_passive"] %></b></td>
      
        <%else%>
        <td><%= record["account"] %></td>
        <td><%= record["in_assets"] %></td>
        <td><%= record["in_passive"] %></td>
        <td><%= record["credit"] %></td>
        <td><%= record["debit"] %></td>
        <td><%= record["out_assets"] %></td>
        <td><%= record["out_passive"] %></td>
      <%end%>
      </tr>
    <%end%>
  <% end %>


</table>

<%= link_to 'Back', data_path , :style=>'color: blue;'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UploadFile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>